version: '2.3'
services:
  video-streaming-server:
    # Rtmp to http streaming server
    # https://github.com/alfg/docker-nginx-rtmp
    image:
      alfg/nginx-rtmp:latest
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    # OPTIONAL: Use certificates for SSL encryption
    # volumes:
    #   - type: bind
    #     source: ./certs
    #     target: /opt/certs

  darknet-video-webcam:
    build: .
    runtime: nvidia
    image: darknet-classic:latest
    restart: always
    volumes:
      - type: bind
        source: ./python-test.py
        target: /python-test.py
      - type: bind
        source: ./darknet/cfg
        target: /cfg
      - type: bind
        source: ./darknet/data
        target: /data
      - type: bind
        source: ./weights
        target: /weights
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /tmp/.docker.xauth
        target: /tmp/.docker.xauth

    environment:
      USE_ENV: 1
      OUTPUT_URI: rtmp://video-streaming-server:1935/stream/webcam-processed
      SOURCE_URI: /dev/video0
      DARKNET_CFG_PATH: /cfg/yolov3-tiny.cfg
      DARKNET_WEIGHTS_PATH: /weights/yolov3-tiny.weights
      DARKNET_COCO_DATA_PATH: /cfg/coco.data
      SHOW_OUTPUT: 1
      STREAM_SOURCE: 1
      DISPLAY: $DISPLAY